name: gcr-gpu
channels:
  - nvidia/label/cuda-12.2.0
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alembic=1.16.4=py39h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - colorlog=5.0.1=py39h06a4308_1
  - comm=0.2.1=py39h06a4308_0
  - contourpy=1.2.1=py39hdb19cb5_1
  - cuda-cccl=12.2.53=0
  - cuda-command-line-tools=12.2.0=0
  - cuda-compiler=12.2.0=0
  - cuda-cudart=12.2.53=0
  - cuda-cudart-dev=12.2.53=0
  - cuda-cudart-static=12.2.53=0
  - cuda-cuobjdump=12.2.53=0
  - cuda-cupti=12.2.60=0
  - cuda-cupti-static=12.2.60=0
  - cuda-cuxxfilt=12.2.53=0
  - cuda-documentation=12.2.53=0
  - cuda-driver-dev=12.2.53=0
  - cuda-gdb=12.2.53=0
  - cuda-libraries=12.2.0=0
  - cuda-libraries-dev=12.2.0=0
  - cuda-libraries-static=12.2.0=0
  - cuda-nsight=12.2.53=0
  - cuda-nsight-compute=12.2.0=0
  - cuda-nvcc=12.2.91=0
  - cuda-nvdisasm=12.2.53=0
  - cuda-nvml-dev=12.2.81=0
  - cuda-nvprof=12.2.60=0
  - cuda-nvprune=12.2.53=0
  - cuda-nvrtc=12.2.91=0
  - cuda-nvrtc-dev=12.2.91=0
  - cuda-nvrtc-static=12.2.91=0
  - cuda-nvtx=12.2.53=0
  - cuda-nvvp=12.2.60=0
  - cuda-opencl=12.2.53=0
  - cuda-opencl-dev=12.2.53=0
  - cuda-profiler-api=12.2.53=0
  - cuda-sanitizer-api=12.2.53=0
  - cuda-toolkit=12.2.0=0
  - cuda-tools=12.2.0=0
  - cuda-version=12.9=h4f385c5_3
  - cuda-visual-tools=12.2.0=0
  - cudnn=8.9.7.29=h092f7fd_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.11=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py39h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gds-tools=1.7.0.149=0
  - graphite2=1.3.14=h295c915_1
  - greenlet=3.1.1=py39h6a678d5_0
  - h5py=3.14.0=py39he0d80d8_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.5.0=py39h06a4308_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - ipykernel=6.29.5=py39h06a4308_1
  - ipython=8.15.0=py39h06a4308_0
  - jedi=0.19.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=py39h06a4308_0
  - jupyter_core=5.8.1=py39h06a4308_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libcublas=12.2.1.16=0
  - libcublas-dev=12.2.1.16=0
  - libcublas-static=12.2.1.16=0
  - libcufft=11.0.8.15=0
  - libcufft-dev=11.0.8.15=0
  - libcufft-static=11.0.8.15=0
  - libcufile=1.7.0.149=0
  - libcufile-dev=1.7.0.149=0
  - libcufile-static=1.7.0.149=0
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.3.53=0
  - libcurand-dev=10.3.3.53=0
  - libcurand-static=10.3.3.53=0
  - libcurl=8.14.1=hc1efc7f_1
  - libcusolver=11.5.0.53=0
  - libcusolver-dev=11.5.0.53=0
  - libcusolver-static=11.5.0.53=0
  - libcusparse=12.1.1.53=0
  - libcusparse-dev=12.1.1.53=0
  - libcusparse-static=12.1.1.53=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.1.1.14=0
  - libnpp-dev=12.1.1.14=0
  - libnpp-static=12.1.1.14=0
  - libnvjitlink=12.2.91=0
  - libnvjitlink-dev=12.2.91=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libnvjpeg-static=12.1.1.14=0
  - libopenblas=0.3.29=ha39b09d_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.2.3=py39h06a4308_0
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib=3.9.2=py39h06a4308_1
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py39hb6b6513_0
  - mpich=4.1.1=hbae89fd_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - nsight-compute=2023.2.0.16=0
  - numexpr=2.10.1=py39hd28fd6d_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=h8e75217_0
  - openssl=3.5.2=h26f9b46_0
  - optuna=4.5.0=pyhd8ed1ab_0
  - packaging=25.0=py39h06a4308_0
  - pandas=2.3.1=py39h277b779_0
  - parso=0.8.4=py39h06a4308_0
  - patsy=1.0.1=py39h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py39h06a4308_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.3.0=py39hb1c3d2d_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pygments=2.19.1=py39h06a4308_0
  - pyparsing=3.2.0=py39h06a4308_0
  - pyqt=6.7.1=py39h8dad735_2
  - pyqt6-sip=13.9.1=py39h6ce4db3_2
  - python=3.9.23=he99959a_0
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=26.2.0=py39h6a678d5_0
  - qtbase=6.7.3=h10a5587_4
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.3=hc2a1206_0
  - setuptools=72.1.0=py39h06a4308_0
  - sip=6.10.0=py39h6a678d5_0
  - six=1.17.0=py39h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlalchemy=2.0.41=py39h00e1ef3_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.5=py39h76ea63d_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py39h06a4308_0
  - tornado=6.5.1=py39h5eee18b_0
  - tqdm=4.67.1=py39h2f386ee_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing-extensions=4.12.2=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_1
  - wcwidth=0.2.13=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - cloudpickle==3.1.1
      - dm-tree==0.1.8
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fsspec==2025.7.0
      - gast==0.6.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - idna==3.10
      - jax==0.4.20
      - jaxlib==0.4.20+cuda12.cudnn89
      - jinja2==3.1.6
      - keras==2.15.0
      - keras-core==0.1.7
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.2.5.6
      - nvidia-cuda-cupti-cu12==12.2.142
      - nvidia-cuda-nvcc-cu12==12.2.140
      - nvidia-cuda-nvrtc-cu12==12.2.140
      - nvidia-cuda-runtime-cu12==12.2.140
      - nvidia-cudnn-cu12==8.9.4.25
      - nvidia-cufft-cu12==11.0.8.103
      - nvidia-curand-cu12==10.3.3.141
      - nvidia-cusolver-cu12==11.5.2.141
      - nvidia-cusparse-cu12==12.1.2.141
      - nvidia-nccl-cu12==2.16.5
      - nvidia-nvjitlink-cu12==12.2.140
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - optree==0.17.0
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - rtdl-num-embeddings==0.0.12
      - scipy==1.12.0
      - sympy==1.14.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io==0.36.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - tensorflow-probability==0.23.0
      - termcolor==3.1.0
      - torch==2.3.1+cpu
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.14.2
prefix: /home/linneamw/anaconda3/envs/gcr-gpu
