name: gcr
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.14.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py39hf3d152e_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=3.0.9=h7f8727e_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=py39h06a4308_0
  - platformdirs=3.8.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - python=3.9.17=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyzmq=19.0.2=py39hb69f2a1_2
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py39hb9d737c_3
  - traitlets=5.9.0=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - cachetools==5.3.1
    - certifi==2023.5.7
    - charset-normalizer==3.2.0
    - cloudpickle==2.2.1
    - contourpy==1.1.0
    - cycler==0.11.0
    - dm-tree==0.1.8
    - flatbuffers==23.5.26
    - fonttools==4.41.0
    - gast==0.4.0
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.56.0
    - h5py==3.9.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.0
    - jax==0.4.13
    - jaxlib==0.4.13+cuda12.cudnn89
    - keras==2.13.1
    - keras-core==0.1.0
    - kiwisolver==1.4.4
    - libclang==16.0.6
    - markdown==3.4.3
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - mdurl==0.1.2
    - ml-dtypes==0.2.0
    - namex==0.0.7
    - numpy==1.24.3
    - nvidia-cublas-cu12==12.2.1.16
    - nvidia-cuda-cupti-cu12==12.2.60
    - nvidia-cuda-nvcc-cu12==12.2.91
    - nvidia-cuda-runtime-cu12==12.2.53
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.8.15
    - nvidia-cusolver-cu12==11.5.0.53
    - nvidia-cusparse-cu12==12.1.1.53
    - nvidia-nvjitlink-cu12==12.2.91
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - pandas==2.0.3
    - patsy==0.5.3
    - pillow==10.0.0
    - protobuf==4.23.4
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==3.0.9
    - pytz==2023.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rich==13.4.2
    - rsa==4.9
    - scipy==1.11.1
    - statsmodels==0.14.0
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - tensorflow==2.13.0
    - tensorflow-estimator==2.13.0
    - tensorflow-io==0.33.0
    - tensorflow-io-gcs-filesystem==0.33.0
    - tensorflow-probability==0.20.1
    - termcolor==2.3.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - urllib3==1.26.16
    - werkzeug==2.3.6
    - wrapt==1.15.0
    - zipp==3.16.2
prefix: /home/linneamw/anaconda3/envs/gcr
